console.log("\x1b[0mThis is Reset\x1b[0m");
console.log("\x1b[1mThis is Bold\x1b[0m");
console.log("\x1b[2mThis is Dim\x1b[0m");
console.log("\x1b[4mThis is Underlined\x1b[0m");
console.log("\x1b[5mThis is Blink\x1b[0m");
console.log("\x1b[7mThis is Reverse\x1b[0m");
console.log("\x1b[8mThis is Hidden\x1b[0m");
console.log("\x1b[30mThis is Black\x1b[0m");
console.log("\x1b[31mThis is Red\x1b[0m");
console.log("\x1b[32mThis is Green\x1b[0m");
console.log("\x1b[33mThis is Yellow\x1b[0m");
console.log("\x1b[34mThis is Blue\x1b[0m");
console.log("\x1b[35mThis is Magenta\x1b[0m");
console.log("\x1b[36mThis is Cyan\x1b[0m");
console.log("\x1b[37mThis is White\x1b[0m");
console.log("\x1b[40mThis is Black background\x1b[0m");
console.log("\x1b[41mThis is Red background\x1b[0m");
console.log("\x1b[42mThis is Green background\x1b[0m");
console.log("\x1b[43mThis is Yellow background\x1b[0m");
console.log("\x1b[44mThis is Blue background\x1b[0m");
console.log("\x1b[45mThis is Magenta background\x1b[0m");
console.log("\x1b[46mThis is Cyan background\x1b[0m");
console.log("\x1b[47mThis is White background\x1b[0m");
